### ISSUE TITLE
直接下载的js实例 无法运行，src目录没有js文件

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw-admin#105]

**Comment by jaywcjlove** [comment]
添加测试用 @SunLxy

**Comment by SunLxy** [comment]
basejs项目实例文件 测试用例

https://github.com/uiwjs/uiw-admin/blob/bd558e81c8860025fd6b9e1fcb019b5d5466fb50/test/copy.test.ts#L1-L9
