### ISSUE TITLE
[ProForm<ProForm 表单>]: 表单中的select参数为0时，getError()方法校验不通过

### ISSUE THREAD

**Issue by Amber-Nan** [uiwjs/uiw-admin#112]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

item类型为select时，select的value参数为0表单getError()方法校验不通过

### 错误复现

重现行为的步骤：

1. ProForm添加item类型为select
2. 使 select 参数为0
3. 触发表单getError()方法校验表单
4. 提示select未选择

**Comment by xingyuefeng** [comment]
https://github.com/uiwjs/uiw/issues/615 uiw form bug
