### ISSUE TITLE
[登录页面]: 登录框可以不出现滚动条

### ISSUE THREAD

**Issue by wangwei88** [uiwjs/uiw-admin#116]
- UIW：[4.13.8]
- 操作系统：[windows]
- 浏览器：[Chrome]
- 版本和构建：[5.2.29]
![image](https://user-images.githubusercontent.com/21116000/157362090-8142ccf0-1638-4f6b-ae5f-dc3d1c128a7d.png)

**Comment by xingyuefeng** [comment]
@wangwei88 可以调整logo 文字样式

**Comment by jaywcjlove** [comment]
@xingyuefeng 建议更改样式，默认剧中，超出高度最外层出现滚动条。
