### ISSUE TITLE
[BasicLayout]希望退出登陆按钮可以有自定义事件

### ISSUE THREAD

**Issue by star-hamster** [uiwjs/uiw-admin#117]
**您的功能请求是否与问题有关？请描述。**

退出时可以清除登陆时存在session中的数据

**描述您想要的解决方案**

退出登陆按钮可以有自定义事件

**Comment by xingyuefeng** [comment]
@didiboji 更新至最新版 BasicLayout 增加`hideLogoutButton` 属性，为ture隐藏默认退出按钮，自己配置退出按钮
