### ISSUE TITLE
[ProTable]: form表单验证onBeforeSearch方法报错

### ISSUE THREAD

**Issue by Amber-Nan** [uiwjs/uiw-admin#118]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

orm表单验证onBeforeSearch方法报错，Property 'filed' does not exist on type 'Error'.

### 错误复现

重现行为的步骤：

1. ProTable组件使用onBeforeSearch验证查询表单
2. 打印无err.filed

### 截图

<img width="787" alt="image" src="https://user-images.githubusercontent.com/66067296/157419393-8f232f63-37aa-4b41-9ad0-0991a9e86cfe.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/66067296/157419564-9e7490be-21b2-4079-8506-683decec71c3.png">

**Comment by xingyuefeng** [comment]
@Amber-Nan 你的例子贴一下  说的是不是uiw form ？ ProForm没这个api

**Comment by Amber-Nan** [comment]
uiw-admin   ProTable组件 @xingyuefeng   
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/66067296/157567157-4d007e9f-2012-40c3-b903-f180d80886d2.png">

**Comment by xingyuefeng** [comment]
@Amber-Nan 这是ts错误 没有给err加类型，可以这样看下

```ts
 const err: any = new Error()

```

**Comment by Amber-Nan** [comment]
已正常使用，可以关闭
