### ISSUE TITLE
[路由菜单 routes]: 刷新页面，二级菜单选中，一级菜单不会展开

### ISSUE THREAD

**Issue by matuancc** [uiwjs/uiw-admin#127]
### 描述错误

选中二级菜单，刷新页面，选中的一级菜单没有展开

### 预期行为

保持选中状态，并展开所在的菜单

### 截图

<img width="499" alt="image" src="https://user-images.githubusercontent.com/33281802/160043460-8ab99665-5392-4661-abbe-9b44d12a9030.png">

### 刷新后

<img width="464" alt="image" src="https://user-images.githubusercontent.com/33281802/160043618-2db7a4c7-5966-4a2b-b1d9-0c585dda327c.png">

### 桌面（请填写以下信息）：

- UIW：4.15.0
- 操作系统：macOS
- 浏览器：火狐

**Comment by xingyuefeng** [comment]
@matuancc  更新至[5.2.38](https://github.com/uiwjs/uiw-admin/commit/6f9bac26293ca676065ba33af37dd347c837e87f)
