### ISSUE TITLE
[BasicLayout]: 文档打不开

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw-admin#130]
[注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

[文档错误地址](https://uiwjs.github.io/uiw-admin/#/basic-layouts?title=%E4%BD%95%E6%97%B6%E4%BD%BF%E7%94%A8)

**Comment by SunLxy** [comment]
doc:更新文档 - 2fd6ca92c2ba60c154496d42dfebd3e8b7abde04
