### ISSUE TITLE
ProTable组件搜索栏列数可以自定义

### ISSUE THREAD

**Issue by rulishu** [uiwjs/uiw-admin#135]
**您的功能请求是否与问题有关？请描述。**

对推荐的新功能，添加清晰简洁的描述。前任。当 [...]

**描述您想要的解决方案**

对您想要发生的事情的清晰简洁的描述。

**描述您考虑过的替代方案**

对您考虑过的任何替代解决方案或功能的清晰简洁的描述。

**附加上下文**

在此处添加有关功能请求的任何其他上下文或屏幕截图。

### 问题清单

完成每个步骤后，在方框中打一个 x。您也可以在创建问题后填写这些内容。如果您不确定其中的任何一个，请随时询问。我们是来帮忙的！这只是提醒我们在回应问题之前要寻找什么。

- [ ] 我已经检查过其他类似的问题
- [ ] 我已经解释了为什么这个改变很重要
- [ ] 我添加了必要的文件（如果适用）

**Comment by rulishu** [comment]
当前是固定的一行五列, 现在想自定义
![20220411101143](https://user-images.githubusercontent.com/68832960/162653692-69c5a43d-3485-44e7-9e0c-1081020ca990.jpg)

**Comment by xingyuefeng** [comment]
@rulishu 更新[@uiw-admin/components v5.3.6](https://www.npmjs.com/package/@uiw-admin/components)

**Comment by jaywcjlove** [comment]
@xingyuefeng 说明更新到 什么版本，如： `v1.12.0+`
