### ISSUE TITLE
ProTable 添加 DateInputRange日期组件查询

### ISSUE THREAD

**Issue by panbibi** [uiwjs/uiw-admin#137]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/81728478/163342857-1aa6545b-6100-48cf-a7fb-19ddf8ff75de.png">

期望：ProTable 可以支持 DateInputRange日期组件查询

**Comment by xingyuefeng** [comment]
@panbibi 更新[@uiw-admin/components](https://www.npmjs.com/package/@uiw-admin/components)
