### ISSUE TITLE
proTable 过长时

### ISSUE THREAD

**Issue by matuancc** [uiwjs/uiw-admin#139]
**您的功能请求是否与问题有关？请描述。**

当底下的table栏过长时，搜索框表单也过长，右侧按钮应该固定

**描述您想要的解决方案**

<img width="1565" alt="image" src="https://user-images.githubusercontent.com/33281802/166862126-2fb06620-4044-4346-aebb-7e394e1a4b04.png">
我觉得外面的大div不应该超出滑动，里面的表单应该在包一个div超出换行

**Comment by xingyuefeng** [comment]
@matuancc 可以设置一行六列或者七列 这样表单宽度会减少

**Comment by matuancc** [comment]
> @matuancc 可以设置一行六列或者七列 这样表单宽度会减少

好的
