### ISSUE TITLE
ProForm 时间输入框在输入时间后删除时间校验没有生效

### ISSUE THREAD

**Issue by panbibi** [uiwjs/uiw-admin#140]
![image](https://user-images.githubusercontent.com/81728478/167247900-5f1696d0-b562-42c9-95d5-704fd017bc72.png)
期望：

**Comment by panbibi** [comment]
在输入时间后清除时间，点击提交可以有红色提示文字

**Comment by xingyuefeng** [comment]
@panbibi 更新 [@uiw-admin/components v5.3.7](https://www.npmjs.com/package/@uiw-admin/components)
