### ISSUE TITLE
头部右侧增加菜单，可使用自定义组件

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw-admin#143]
**您的功能请求是否与问题有关？请描述。**

头部右侧增加菜单，可使用自定义组件

![image](https://user-images.githubusercontent.com/24369183/168503690-395d6a25-14cf-4727-8416-0c4167cd28b3.png)

**Comment by SunLxy** [comment]
@xingyuefeng 这个已经存在自定义功能
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/49544090/168506073-033858b9-368b-4349-95ca-bb4afc91b0db.png">
