### ISSUE TITLE
[UserLogin]: 用户名和密码输入框数据为空时提示错误

### ISSUE THREAD

**Issue by Lingxiaozhu** [uiwjs/uiw-admin#153]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

部分输入账号和密码，提示不对

### 错误复现

重现行为的步骤：

1. 只输入账号，密码为空，点击登录，没有没有提示，同时请求也发送。
2. 只输入密码，账号为空，点击登录，密码输入框也有错误提示
3. fields属性自定义form表单项无法添加错误提示

### 预期行为

能正确对应输入框作出错误提示

### 截图
![image](https://user-images.githubusercontent.com/90493447/169973105-8fd178d1-c4af-4b76-8b6b-83306600c8db.png)

![image](https://user-images.githubusercontent.com/90493447/169972082-a9732541-3615-4cac-8304-5f0aacc5433a.png)

![image](https://user-images.githubusercontent.com/90493447/169973010-900802b3-2390-4d15-b327-675ca717fe22.png)

### 桌面（请填写以下信息）：

- 操作系统：Windows
- 浏览器：Chrome

**Comment by wj0990** [comment]
收到
