### ISSUE TITLE
当前文档不清晰，需要完善补充

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw-admin#92]

**Comment by jaywcjlove** [comment]
@xingyuefeng 需要告知什么文档不清晰，完善那些地方

**Comment by xingyuefeng** [comment]
- 组件的说明、用途文字叙述不够详细,只有简单的组件名字, 例如 [ProDrawer](https://uiwjs.github.io/uiw-admin/#/prodrawer)、[AuthPage](https://uiwjs.github.io/uiw-admin/#/authorized)、[document-title](https://uiwjs.github.io/uiw-admin/#/document-title)
- 组件实例不够完善,组件api有很多，实例较少， 例如 [ProTable](https://uiwjs.github.io/uiw-admin/#/protable)、[basic-layouts](https://uiwjs.github.io/uiw-admin/#/basic-layouts)
- 有的页面组件没有预览界面，只有图 例如 [user-login](https://uiwjs.github.io/uiw-admin/#/user-login)、 [tab 选项卡布局](https://uiwjs.github.io/uiw-admin/#/layout-tabs?title=%E9%A2%84%E8%A7%88)

@ChenlingasMx @SunLxy
